### ISSUE TITLE
Не добавляются файлы в отчёт

### ISSUE THREAD

**Issue by Folko85** [d10xa/allure-spock-geb#2]
Опробовал версию из ветки allure-2. В allure-reports почему-то перемещаются только 1й скриншот и первый файл html из отчёта геба. Но и они не отображаются в итоговом отчёте. Использую таблицу значений spock c аннотацией @Unroll. 
Итоговые файлы в allure-reports вот такие
![Screenshot_20210114_125815](https://user-images.githubusercontent.com/1721835/104575503-30c90500-5668-11eb-83cd-98b99a2eca46.png)
Попробую покопаться в настройках геба, если что выйдет/не выйдет то отпишусь или сделаю PR

**Comment by Folko85** [comment]
К сожалению, так и не вышло запустить данную версию. Однако я примерно понял как это всё работает и переопределил дефолтный репортер, обойдясь без плагина. Вышла довольно специфичная конфигурация, вряд ли кому ещё пригодится. В любом случае, спасибо за проделанный труд.

**Comment by d10xa** [comment]
@Folko85 Можешь показать что ты переопределил?

**Comment by Folko85** [comment]
По факту почти всё 2й аллюр подхватывает сам. Единственно, почему-то мой Allure не хотел работать с параметром useSpock, так что все параметры официального gradle-плагина поставил дефолтные, оставив лишь autoconfigure = true
Сам репортер примерно такой
```

import geb.report.ReportState
import geb.report.Reporter
import geb.report.ReportingListener
import geb.report.ScreenshotReporter
import io.qameta.allure.Allure
import io.qameta.allure.Attachment

class VideoReporter extends ScreenshotReporter implements Reporter {

    String videoPath

    VideoReporter(String videoPath) {
        this.videoPath = videoPath
    }

    @Override
    void writeReport(ReportState reportState) {
        super.writeReport(reportState)
        if (videoPath != null){
            String sessionId = reportState.browser.getDriver().getSessionId()
            videoInHtml(sessionId, videoPath)
        }
    }

    @Override
    void addListener(ReportingListener listener) {
        super.addListener(listener)
    }

    @Attachment(value = "Video HTML", type = "text/html", fileExtension = ".html")
    static String videoInHtml(String sessionId, String remoteVideo) {
        def videoUrl = remoteVideo + sessionId + ".mp4"
        return "<video width='100%' height='100%' controls autoplay><source src='${videoUrl}' type='video/mp4'></video>"
    }

    @Override
    protected File saveScreenshotPngBytes(File outputDir, String label, byte[] bytes) {
        Allure.addAttachment("Screenshot", "text/html", new ByteArrayInputStream(bytes), ".png")
        def file = getFile(outputDir, label, 'png')
        file.withOutputStream { it << bytes }
        file
    }
}

```
Собственно я сюда добавил аттач для видео, записанного селеноидом (оно там доступно по определённому юрлу и называется по sessionId). Не факт, что где-то ещё это будет работать. А для аттача скринов переопределил стандартный метод, добавив одну строчку - Allure.addAttachment("Screenshot", "text/html", new ByteArrayInputStream(bytes), ".png") Собственно добавить репортер в GebConfig можно строчкой reporter = new VideoReporter (videoPath). Кроме скринов и видео мне было ничего не нужно, но думаю, если ещё что-то придётся добавлять, то это проблемой не будет.
